[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

[dependencies]
forge-std = "1.14.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
